base:
  random_state: 47
  target_col: quality

data_source:
  local_path: "C:\\Users\\Sainadh\\Downloads\\winequality-red.csv"

split:
  dir: data/split
  train_file: train.csv
  test_file: test.csv
  split_ratio: 0.20

process:
  dir: data/processed
  train_file: final_train.csv
  test_file: final_test.csv

train:
  n_est: 25
  
model_dir: model
